### ISSUE TITLE
Supporting yaml key value pairs

### ISSUE THREAD

**Issue by razilevin** [Ashald/EnvFile#124]
Hello,

I know your plugin supports yaml file format. It works when the structure is flat

```yaml
server.port: "9090"
elastic.search.products.index: products-current
management.server.port: "8082"
spring.cloud.config.enabled: "true"
```

But fails with a class cast exception LinkedHashMap cannot be cast to String when I use yaml key value pairs.

```yaml
server:
  port: "9090"
```

Makes sense when you think about it just wondering if I am missing something.

Thank You
