### ISSUE TITLE
EnvFile won't turn off in run config

### ISSUE THREAD

**Issue by centum** [Ashald/EnvFile#193]
EnvFile is disabled in run config, but it still passes IDE environment variables to docker-compose config.

<img width="555" alt="Screenshot 2022-10-04 at 14 48 53" src="https://user-images.githubusercontent.com/926423/193821928-74588f0b-dd05-4dd9-8118-a9117f80ebbe.png">

Example IDE overrode docker compose config **with installed EnvFile** but disabled on run config:
```
version: "3.9"
services:
  app:
    command:
    - "python"
    - "/opt/.pycharm_helpers/pycharm/_jb_pytest_runner.py"
    - "--path"
    - "/opt/project/"
    - "--"
    - "--no-cov"
    environment:
      PATH: "/usr/local/Cellar/pyenv-virtualenv/1.1.5/shims:/Users/vadim/.pyenv/shims:/Users/vadim/Workspace/go/bin:/Users/vadim/.cargo/bin:/Users/vadim/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin"
      PYENV_SHELL: "zsh"
      STARSHIP_SHELL: "zsh"
      VIRTUALENVWRAPPER_WORKON_CD: "1"
      LOGNAME: "vadim"
      XPC_SERVICE_NAME: "application.com.jetbrains.intellij.8768099018.8805781595"
      PYCHARM_HOSTED: "1"
      PYCHARM_DISPLAY_PORT: "63342"
      __CFBundleIdentifier: "com.jetbrains.intellij"
      PYENV_VIRTUALENV_INIT: "1"
      PYTHONPATH: "/opt/.pycharm_helpers/pycharm:/opt/project:/opt/project:/opt/.pycharm_helpers/pycharm_matplotlib_backend:/opt/.pycharm_helpers/pycharm_display"
      SHELL: "/bin/zsh"
      PYTHONIOENCODING: "UTF-8"
      PYTEST_RUN_CONFIG: "True"
      PIP_DOWNLOAD_CACHE: "/Users/vadim/.pip/cache"
      OLDPWD: "/"
      GOPATH: "/Users/vadim/Workspace/go"
      USER: "vadim"
      VIRTUALENVWRAPPER_HOOK_DIR: "/Users/vadim/.virtualenvs"
      TMPDIR: "/var/folders/rq/w1tygkgx1_3_2fc6rrc8lnhm0001gn/T/"
      PYCHARM_HELPERS_DIR: "/opt/.pycharm_helpers/pycharm"
      PYTHONUNBUFFERED: "1"
      XPC_FLAGS: "0x0"
      VIRTUALENVWRAPPER_PROJECT_FILENAME: ".project"
      PYCHARM_DISPLAY_HTTP_PROXY: "http://host.docker.internal:63342"
      __CF_USER_TEXT_ENCODING: "0x1F5:0x0:0x2"
      PROJECT_HOME: "/Users/vadim/Workspace"
      PYENV_VIRTUALENV_DISABLE_PROMPT: "1"
      LC_CTYPE: "en_GB.UTF-8"
      HOME: "/Users/vadim"
    ports: []
    stdin_open: true
    volumes:
    - "/Users/vadim/Workspace/project1:/opt/project:rw"
    - "pycharm_helpers_IU-222.4167.29:/opt/.pycharm_helpers"
    working_dir: "/opt/project/"
volumes:
  pycharm_helpers_IU-222.4167.29: {}
```
Example IDE overrode docker compose config **without installed EnvFile**:
```
version: "3.9"
services:
  app:
    command:
    - "python"
    - "/opt/.pycharm_helpers/pycharm/_jb_pytest_runner.py"
    - "--path"
    - "/opt/project/"
    - "--"
    - "--no-cov"
    environment:
      PYTHONPATH: "/opt/.pycharm_helpers/pycharm:/opt/project:/opt/project:/opt/.pycharm_helpers/pycharm_matplotlib_backend:/opt/.pycharm_helpers/pycharm_display"
      PYTHONUNBUFFERED: "1"
      PYCHARM_DISPLAY_HTTP_PROXY: "http://host.docker.internal:63342"
      PYTHONIOENCODING: "UTF-8"
      PYTEST_RUN_CONFIG: "True"
      PYCHARM_HOSTED: "1"
      PYCHARM_DISPLAY_PORT: "63342"
      PYCHARM_HELPERS_DIR: "/opt/.pycharm_helpers/pycharm"
    ports: []
    stdin_open: true
    volumes:
    - "/Users/vadim/Workspace/project1:/opt/project:rw"
    - "pycharm_helpers_IU-222.4167.29:/opt/.pycharm_helpers"
    working_dir: "/opt/project/"
volumes:
  pycharm_helpers_IU-222.4167.29: {}
```
The configurations above must be equal, and system environment variables don't pass to docker containers.

EnvFile: v3.4.0
IntelliJIdea 2022.2
