### ISSUE TITLE
Allow Kubernetes yaml style

### ISSUE THREAD

**Issue by girafi** [Ashald/EnvFile#218]
We have lots of Kubernetes config files in yaml that list the env vars in the following style:

```
env:
- name: MY_KEY_1
  value: "value1"
- name: MY_KEY_2
  value: "value2"
```

We would love to also use the same yaml locally for running with your gorgeous and awesome fancy envVar plugin.
Converting them to yaml dictionary is unfornunately quite a step always

Thanks for your care!
